function FAWWCSWomensS6 = importfile_DataViz(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  FAWWCSWOMENSS6 = IMPORTFILE(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a table.
%
%  FAWWCSWOMENSS6 = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  FAWWCSWOMENSS6 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  FAWWCSWomensS6 = importfile_DataViz("/Users/iMacPro/Library/CloudStorage/OneDrive-SwanseaUniversity/Research/WIPS/FAW/FAW WCS Womens.xlsx", "Roll_file", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Dec-2023 11:42:19

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 57);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["Name", "Fixture", "PLAYER_METADATA", "Threshold", "Distance_TH_0", "Time_TH_0", "Epoch", "Frequency_TH_0", "Distance_TH_1", "Time_TH_1", "Frequency_TH_1", "Distance_TH_2", "Time_TH_2", "Frequency_TH_2", "Distance_TH_3", "Time_TH_3", "Frequency_TH_3", "Distance_TH_4", "Time_TH_4", "Frequency_TH_4", "Distance_TH_5", "Time_TH_5", "Frequency_TH_5", "Distance_TH_6", "Time_TH_6", "Frequency_TH_6", "Distance_TH_7", "Time_TH_7", "Frequency_TH_7", "Distance_TH_8", "Time_TH_8", "Frequency_TH_8", "Index", "DistMmin", "HSRMmin", "SprMmin", "A1Frmin", "A2Frmin", "A3Frmin", "D1Frmin", "D2Frmin", "D3Frmin", "AgeGroupyear", "DOB", "RelativeAge", "BirthQuartile", "Round", "MDNumber", "MatchDate", "homeaway", "location", "Formation", "result", "Position", "PositionalGroup", "KOTime", "starterfinisher"];
opts.VariableTypes = ["categorical", "categorical", "categorical", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "datetime", "string", "string", "categorical", "double", "datetime", "categorical", "categorical", "categorical", "categorical", "string", "categorical", "double", "categorical"];

% Specify variable properties
opts = setvaropts(opts, ["AgeGroupyear", "RelativeAge", "BirthQuartile", "Position"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Name", "Fixture", "PLAYER_METADATA", "Threshold", "AgeGroupyear", "RelativeAge", "BirthQuartile", "Round", "homeaway", "location", "Formation", "result", "Position", "PositionalGroup", "starterfinisher"], "EmptyFieldRule", "auto");

% Import the data
FAWWCSWomensS6 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    FAWWCSWomensS6 = [FAWWCSWomensS6; tb]; %#ok<AGROW>
end

end